services:
  mysql:
    image: 'mysql:${MYSQL_IMAGE_TAG:-8.4}'
    container_name: '${MYSQL_CONTAINER_NAME:-we-ai-mysql}'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME:-we_ai}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD:-weai1234}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root1234}'
      - 'MYSQL_USER=${DB_USERNAME:-weai}'
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - 'we-ai-mysql-data:/var/lib/mysql'

volumes:
  we-ai-mysql-data:
