spring:
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
